### ISSUE TITLE
Embeddable charts

### ISSUE THREAD

**Issue by kiwicopple** [supabase/repository.surf#1]
# Feature request

It would be awesome if you could embed charts into other sites (with a `Powered by ..` of course)

**Comment by kiwicopple** [comment]
btw - this isn't urgent at all. I just wanted to get it down

**Comment by joshenlim** [comment]
With reference to the PR:

Allows iframe embedding of our charts, demo: https://codepen.io/joshenlim/pen/oNzpeLZ?editors=1000

Done via this url: http://localhost:3000/supabase/supabase?embed=true&type=[chartType]

Where chart type is currently either issues or stars

**Comment by joshenlim** [comment]
Confirmed that iframe embedding works in Chrome and Safari but fails in Firefox - investigating why
