### ISSUE TITLE
The numbers on the star history graph are sometimes cut off

### ISSUE THREAD

**Issue by ykdojo** [supabase/repository.surf#18]
### How to reproduce this bug

Open vercel -> next.js. The numbers on the left are cut off like this:

![image](https://user-images.githubusercontent.com/1811651/103141618-a1a18080-46ab-11eb-86a5-60e8339ca9dd.png)

**Comment by joshenlim** [comment]
Fixed in https://github.com/supabase/repository.surf/commit/89cbcd51d9661a6eccc7b26ef6bc38e28b510fc3
