### ISSUE TITLE
Implement search for repositories in the side bar

### ISSUE THREAD

**Issue by joshenlim** [supabase/repository.surf#32]
# Feature request

At the moment due to the github's api's pagination per_page limitation of max 100, we only show 100 repositories in the side panel - most organizations have more than 100.

However it isn't optimal as well to paginate through the api and throw all the repositories in the side panel as some organizations like Google has 1.9k repos. I feel the best way is to implement a search field and only display max 100 results in the side bar.

- Will need to think in terms of UX where is best to have the search field
- Search should have debouncing
- If possible, we need to fix the message on the organization page as well "Timeline of issues across xxx repos", atm max will be 100 which may be inaccurate

We may need to start being careful about our API rate limits too

**Comment by ykdojo** [comment]
An idea about how we might be able to implement this:

What if, every time a user loads one of the pages for an organization, we load all the repo names onto the client? If we're worried about the API limit, we can cache this list in SB.

That way, filtering/searching through the repo names will be really quick. With this approach, we can solve #41 at the same time, too. Plus, having an array of 2000 short strings (and maybe their star counts) loaded on the client isn't going to be that expensive.

**Comment by ykdojo** [comment]
Another idea:

Limit the number of repos shown to 100 by default (the 100 most starred ones). Then, if someone wants to see more, get them to pay a bit 😛

**Comment by kiwicopple** [comment]
> Limit the number of repos shown to 100 by default (the 100 most starred ones). Then, if someone wants to see more, get them to pay a bit 😛

Agree with this approach!

**Comment by kiwicopple** [comment]
Just thinking about structuring the site too:

Perhaps we also do away with the `/[org]/[repo]` and the sidebar just becomes a "filter bar." 
Essentially there is only one page (`/[org]`), which might have some filter parameters appended to the URL:

- `repository.surf/supabase`: shows all repos
- `repository.surf/supabase?r=supabase,infrastructure,supabase-js`: only some selected.

The URL might get very long though - may be better not to append the filters to the URL (but it would make chart embedding easier).

Just a suggestion

**Comment by ykdojo** [comment]
> The URL might get very long though - may be better not to append the filters to the URL (but it would make chart embedding easier).

With this approach, maybe we can store a map/table of a shortened URL parameter to a list of selected repos in SB?

So the table could look like:

organization (primary key), uuid (primary key), selected_repos (json)
supabase, j309j2jjf, ['supabase', 'infrastructure', 'supabase-js']
supabase, oj309j0, ['supabase', 'supabase-js']
