### ISSUE TITLE
Allow GitHub org owners to "Claim" an organisation

### ISSUE THREAD

**Issue by kiwicopple** [supabase/repository.surf#33]
# Feature request

## Is your feature request related to a problem? Please describe.

As a github org owner, I want to be able to manage what is visible, and provide my own Developer Key so that this repo can track issues for private organisations.

## Describe the solution you'd like

- Add Auth - GitHub login
- Ability to "Claim" an org - perhaps we can know already if they are the owner of the GitHub org based on their github handle?
- Add some settings
   - GitHub Token (should be hashed)
   - Choose whether issue tracking is turned on for repos 
   - Choose whether private repos should be visible  to the public (right now everyone can see our `infrastructure` repo), or just to people inside the same github org
   
We can use the owner's github token so that we aren't maxing out our own each day

**Comment by joshenlim** [comment]
I'll try plan out the flow for this first

**Comment by joshenlim** [comment]
Drafted out a state diagram:

![image](https://user-images.githubusercontent.com/19742402/103639798-dfdf4f80-4f89-11eb-9958-4b98a4e7edaf.png)

Question:
- In terms of "Claiming an organization" do we allow this just for organization owners? Or anyone that's under the organization?
- Toggling issues tracking, Toggling private repo visiblity, Github access token -> probably save these configs into our DB? Maybe under a table `organizations` with the columns `name (text)`, `issues_tracking (boolean)`, `show_private_repos(boolean)`, `github_access_token(text) - hashed`?
