### ISSUE TITLE
When hovering over the star history graph, it should show the date only

### ISSUE THREAD

**Issue by ykdojo** [supabase/repository.surf#5]
Currently, it shows both date and time, and the time seems somewhat random (sometimes 4pm and other times 5pm on my local environment):
![image](https://user-images.githubusercontent.com/1811651/103073106-ddd5c380-457b-11eb-9da3-41b82ea74610.png)

**Comment by joshenlim** [comment]
I'll make it as a prop to show date only or both - it makes sense to show date only for star history cause i'm doing a groupby on the star events by date. But for issues tracking we're the lambda fires hourly so its better to show the time as well
