### ISSUE TITLE
Stars chart for embed no longer working

### ISSUE THREAD

**Issue by joshenlim** [supabase/repository.surf#58]
# Bug report

Charts can be embedded via the following url for example:

repository.surf/supabase/supabase/embed?chart=stars

Think the stars chart is broken due to the changes we've done for star retrieval. Will need to bring the changes over from index.js to embed.js.

**Comment by joshenlim** [comment]
@ykdojo might need your help on this - we'll just need to pull the star history for a specified repo

**Comment by ykdojo** [comment]
@joshenlim ok I'll take a look. thanks for letting me know!

**Comment by ykdojo** [comment]
@joshenlim Just checked [this page](https://repository.surf/supabase/supabase/embed?chart=stars). It looks like it's working?
