### ISSUE TITLE
Allow users to navigate to other organizations without having to go back to the landing page

### ISSUE THREAD

**Issue by joshenlim** [supabase/repository.surf#61]
# Feature request

At the moment, on the organization page, to view another organization's page, users have to go back to the landing page (either by the provided back button in the UI, or browser back button) to key in another organization

Allow users to do this action without having to traverse back to the landing page

And idea is to leverage on tailwindui's nav bar?

**Comment by kiwicopple** [comment]
Could use this one: 

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/10214025/103667601-1c727180-4fb1-11eb-94fe-f9b561f7d8a7.png">


- stretech the search bar out
- add login/filter buttons on the right(?)
- the subnav can scroll to the relevant sections "Stars", "Issues", "Contributors" etc

**Comment by joshenlim** [comment]
Been thinking about how to fit in this nav bar with our current UI - it's a little awkward combining this with our current side bar:

- We'll have 2 UIs indicating the current organization 

- Having the "repository.surf/org" input within the right segment of the app, which shows the organization/repository information, feels a little out of place. The input feels like it should be traversing within the org context, rather than traversing across orgs (not sure if this makes sense)

- It's also a little hard to squeeze in a two layer nav bar with our side bar, i feel that it'll make the "layout" of the site cluttered too.

![image](https://user-images.githubusercontent.com/19742402/103675402-db7f5a80-4fba-11eb-995e-aee6f1f68186.png)

**Comment by joshenlim** [comment]
I'm thinking along these lines:

- Hovering over the top left corner whether the organization info will show two actions
  - One to link to the org's github page
  - One to change the organization

![image](https://user-images.githubusercontent.com/19742402/103676268-d5d64480-4fbb-11eb-9e34-60657ecb226e.png)

- Click on the second icon will then show the "repository.surf/org" input as such
  - There'll be an "x" to cancel, or even a simple keyboard shortcut "esc" to cancel
  - Could probably even throw in the repo surf logo there too

![image](https://user-images.githubusercontent.com/19742402/103676374-f8685d80-4fbb-11eb-8c84-24d81d6b76bc.png)

wdyt?

**Comment by kiwicopple** [comment]
This one is quite nice

<img width="735" alt="image" src="https://user-images.githubusercontent.com/10214025/103682824-58630200-4fc4-11eb-82de-b75c5d966aac.png">


But I actually think the left sidebar should be removed - it's taking up a lot of real estate, and most of the time the repositories are collapsed. I'd consider instead making it a slideout or collapsible menu (on the right?) with a button in the nav bar to "toggle filters"

Then use the whole page to fill it with pretty graphs. This will work better on mobile to IMO

**Comment by kiwicopple** [comment]
Maybe something like this? 

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/10214025/103683768-957bc400-4fc5-11eb-9520-b7e8694a3c0f.png">

**Comment by joshenlim** [comment]
Ahh okay, yeah agreed about the sidebar, gotcha on this! I'll probably do a mock up on sketch with reference to ^ before starting dev on this
