### ISSUE TITLE
Add a footer with some links and supabase branding

### ISSUE THREAD

**Issue by joshenlim** [supabase/repository.surf#62]
# Feature request

We probably can add these stuffs in 2 areas: landing page + side bar

Will need to confirm exactly what links to add, what I can think of are:
- Github Icon that links to the repo
- Powered by supabase that links to supabase's site
- Throw in the created logo for repo surf too maybe?

**Comment by kiwicopple** [comment]
I enabled Discussions for this repo too! https://github.com/supabase/repository.surf/discussions

> Throw in the created logo for repo surf too maybe?

Defo

**Comment by joshenlim** [comment]
oooh nice! will update the URL in the issue tracker modal to point to repo surf discussions

**Comment by joshenlim** [comment]
Thinking of going with a simple footer for now perhaps - 3 links

Powered by -> supabase site
Twitter -> supabase twitter
Github -> repo surf github repo

![image](https://user-images.githubusercontent.com/19742402/103982292-2b7a3f00-51be-11eb-9d79-e2b6210a22a2.png)

**Comment by joshenlim** [comment]
Similarly for the landing page

![image](https://user-images.githubusercontent.com/19742402/103982496-8f046c80-51be-11eb-97d5-7c738a9fb472.png)

**Comment by joshenlim** [comment]
Have pushed this up: https://github.com/supabase/repository.surf/commit/f7b021ce111ce04ba5da3cf044a66ed75d90f599

But i'll leave this issue open for a couple days if anyone has any feedback to improve this

**Comment by kiwicopple** [comment]
lgtm!
