### ISSUE TITLE
Implement Github Auth login

### ISSUE THREAD

**Issue by joshenlim** [supabase/repository.surf#69]
# Feature request

Ties in with https://github.com/supabase/repository.surf/issues/33

Just breaking down sub tasks

**Comment by joshenlim** [comment]
@kiwicopple Are we able to use supabase's oauth app? I'm gonna create one under my own github profile for now while testing and implementing

**Comment by kiwicopple** [comment]
Hey for this one we should use Supabase Auth - no Auth0 at all. If someone wants to clone the repo they should be able to use this with "only" supabase + github

You'll need to add a github org (you can transfer the org to Supabase before going live)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10214025/103995896-0b557a80-51d4-11eb-9f59-4ac0385c1e70.png">

**Comment by joshenlim** [comment]
Ahhh okay gotcha!

**Comment by joshenlim** [comment]
Leaving some notes for myself and also if anyone might have an idea:

Small issue trying to get all organizations of the logged in user
- `/users/{username}/org` endpoint from Github only returns public memberships to orgs
- `/user/orgs` returns all memberships to orgs (pvt or public) but requires some form of authentication with Github that I can't figure out atm apart from having to provide the user's github access token when making the API call. Access tokens seems to (not too sure?) only be able to be generated manually through the user's github profile

**Comment by kiwicopple** [comment]
Perhaps when you set up the GitHub App you can set the scope of permissions? I can't remember exactly but I think you will need the app to have full org permissions

**Comment by joshenlim** [comment]
Ahh gotcha - I previously set up an oauth app. Am giving github app a shot now

^ based on the permissions, will the data be returned within `supabase.auth.user()`? I've set all permissions under `org` as read only

![image](https://user-images.githubusercontent.com/19742402/104034545-f8f73300-520b-11eb-8861-e6ba10ac5ad8.png)

**Comment by joshenlim** [comment]
A bit of progress from some digging: just jotting some notes down

- Doesn't matter if i use Github App or OAuth app, both work fine
- Github App does not have permissions to read the organizations of the user
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/permissions-required-for-github-apps#permission-on-emails 
- Found a solution with following this https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#web-application-flow
  - Step 1: GET to github/login/oauth/authorize?client_id=...&scope=...
    - Specify `read:org` as scope -> key to getting organizations 
    - User has to grant or request permissions as per screenshot for each organization they are in
![image](https://user-images.githubusercontent.com/19742402/104047399-8b073780-521c-11eb-933f-fe35f03d9d98.png)
    - No grant/permissions, the org will NOT be returned at the end when we do `/user/orgs`
