### ISSUE TITLE
The "Stars" and "Issues" headers are not clickable

### ISSUE THREAD

**Issue by ykdojo** [supabase/repository.surf#74]
I noticed that the "Stars" and "Issues" headers on the new UI are not clickable. Were they meant to be clickable?

![image](https://user-images.githubusercontent.com/1811651/103974767-5a91a180-5127-11eb-92d5-18e90def8ff6.png)

**Comment by joshenlim** [comment]
oh damn this slipped my mind haha

**Comment by ykdojo** [comment]
Haha no worries!

**Comment by joshenlim** [comment]
Resolved via https://github.com/supabase/repository.surf/commit/cb26859cefa58ed8c6e98f689b067654f86b76c6
