### ISSUE TITLE
Growth statistics for "past day" showing 0

### ISSUE THREAD

**Issue by ykdojo** [supabase/repository.surf#75]
When I go to http://\<url\>/supabase and select all repos, the growth statistics for "Past day" shows 0 even though I don't think it should be 0.

I feel like we could simply remove the whole section now that we have "daily new counts"? Or, alternatively, I feel like we should show "Past week" and "Past 30 days", and then compare them to the previous 1 week period and 1 month period, respectively.

**Comment by joshenlim** [comment]
Ooh can i check - cause for me its showing 7 when all repos are selected 

![image](https://user-images.githubusercontent.com/19742402/103976180-fe735f80-51b0-11eb-8fb8-a39c859f399b.png)

Gotcha on the second point too - good one! yeah we can compare with the previous "periods" and show the indication like issues

**Comment by ykdojo** [comment]
Hmm I'm not sure why it's not showing the correct info on my end. It looks like this (the monthly info's also different):
![image](https://user-images.githubusercontent.com/1811651/103976339-5ff0eb00-512b-11eb-9169-0548e9c6c587.png)

**Comment by ykdojo** [comment]
Anyway I think I can look into this issue tomorrow!

**Comment by joshenlim** [comment]
oooh thats really odd 🤔 

but can do! thanks so much @ykdojo!

**Comment by ykdojo** [comment]
I just checked repository.surf, and I still see the same thing:
![image](https://user-images.githubusercontent.com/1811651/104061758-0f6ea180-51ae-11eb-9c0e-ebd83c47573b.png)

I'm assuming @joshenlim doesn't have a problem with it. Maybe it's a timezone thing? Will look into it.
