### ISSUE TITLE
When not all repos are loaded, none of the repos are available

### ISSUE THREAD

**Issue by ykdojo** [supabase/repository.surf#78]
Example: Go to Microsoft's page. When TypeScript's repo is not completely loaded, when you select one of the other repos, it says "Preparing star history... 1 out 1 repos loaded" but it doesn't show the graph.

Also, when a single repo is selected, it should start showing the partial graph even when the data is not completely loaded yet.

**Comment by joshenlim** [comment]
Ahh yes i recall that the org and repo page graphs load slightly differently - might need you to take a look at this one!

**Comment by ykdojo** [comment]
@joshenlim ok cool I'm going to assign myself to this one then 🙂

**Comment by ykdojo** [comment]
Another related issue I found: when you select a repo that's loading and deselect it, it shows something like "0 out of 0 repos loading..." with a loader.
